SELECT 
C.NAME
,COUNT(1) AS 'Last 60 Days'
FROM 
ReportServer.DBO.EXECUTIONLOG (NOLOCK) EL 
INNER JOIN ReportServer.DBO.CATALOG (NOLOCK) C ON EL.REPORTID=C.ITEMID
--WHERE EL.USERNAME NOT IN
GROUP BY C.NAME
ORDER BY COUNT(1) DESC